<?php
    $this->headTitle($this->msgAdminTitle);
    $this->partial('js_grid_includes.phtml',null,$this);
    $this->headScript()->appendScript($this->render('admin/index/js/grid.js'));
?>
<div id="main">
	<div class="content">
		<div id="head">
			<h2><?= $this->msgAdminTitle ?></h2>
		</div>
		<div id="grid-row">
			<table id="jqgridtable" class="scroll" cellpadding="0" cellspacing="0"></table>
			<div id="jqgridpager" class="scroll" style="text-align:center;"></div>
		</div>
	</div>
</div>
