<?php
	$this->headTitle('Доступ запрещен!');
?>
<div class="pathway_box">
	<div class="pathway_part1">
		<div class="pw_left"></div>
		<div class="pw_arrow"></div>
		Авторизация
	</div>
	<div class="pathway_part2">
		Доступ запрещен!
		<div class="pw_right"></div>
	</div>
</div>

<table class="content_table">
	<thead>
		<tr>
			<td>
				<div class="left_border"></div>
				<div class="right_border"></div>
				<div>Авторизация</div>
			</td>

		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="table_first_cell content_cell">
				<p class="error">Доступ запрещен!</p>
			</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
			<td>
				<div class="left_border"></div>
				<div class="right_border"></div>
			</td>
		</tr>
	</tfoot>
</table>