<?php
    $this->headTitle($this->msgAdminTitle);
    $this->partial('js_grid_includes.phtml',null,$this);
    $this->headScript()->appendScript($this->render('admin/tags/js/grid.js'));
	$this->headScript()->appendScript('var GridBaseUrl = "'.$this->getUrl("/admin/module/content/tags/").'";');
?>
<div id="main">
	<div class="content">
		<div id="head">
			<h2><?= $this->msgAdminTitle ?></h2>
		</div>
		<div id="add-button-row">
			<div class="control">
				<?php if($this->checkPermission('content', 'admin_tags', 'add')): ?>
					<span class="button" id="add-button">
	                    <a href="<?php echo $this->getUrl('/admin/module/content/tags/add'); ?>" class="add-action"><?= $this->msgButtonAdd ?></a>
					</span>
				<?php endif; ?>
			</div>
		</div>
		<br />
		<div id="grid-row">
			<table id="jqgridtable" class="scroll" cellpadding="0" cellspacing="0"></table>
			<div id="jqgridpager" class="scroll" style="text-align:center;"></div>
		</div>
	</div>
</div>
