<?php
	$this->headTitle($this->msgAdminViewTitle);
    $this->headScript()->appendScript($this->render('admin/news/js/view.js'));
?>
<div id="main">
	<div class="content">
		<div id="head">
			<h2><?= $this->msgAdminViewTitle ?></h2>
		</div>
        <div class="control">
            <span class="button reset">
                <a href="<?php echo $this->getUrl($this->baseUrl); ?>" class="cancel-action"><?= $this->msgButtonBack ?></a>
            </span>
        </div>
		<div id="viewContent">
			<table>
                <tr>
                    <td class="title"><?= $this->translate('news-admin-form-public-date') ?></td>
                    <td class="value"><?= $this->controller->getListItemValue($this->dataRow, 'public_date'); ?></td>
                </tr>
                <tr>
                    <td class="title"><?= $this->translate('news-admin-form-activated') ?></td>
                    <td class="value"><?= $this->controller->getListItemValue($this->dataRow, 'activated'); ?></td>
                </tr>
                <tr>
                    <td class="title"><?= $this->translate('news-admin-form-is-hot') ?></td>
                    <td class="value"><?= $this->controller->getListItemValue($this->dataRow, 'is_hot'); ?></td>
                </tr>
                <tr>
                    <td class="title"><?= $this->translate('news-admin-form-user-id') ?></td>
                    <td class="value"><?= $this->controller->getListItemValue($this->dataRow, 'user_id'); ?></td>
                </tr>
                <tr>
                    <td class="title"><?= $this->translate('news-admin-form-category-id') ?></td>
                    <td class="value"><?= $this->controller->getListItemValue($this->dataRow, 'category_id'); ?></td>
                </tr>
				<tr>
					<td class="title"><?= $this->translate('news-admin-form-title') ?></td>
					<td class="value"><?= $this->controller->getListItemValue($this->dataRow, 'title'); ?></td>
				</tr>
				<tr>
					<td class="title"><?= $this->translate('news-admin-form-image') ?></td>
					<td class="value"><?= $this->controller->getListItemValue($this->dataRow, 'image'); ?></td>
				</tr>
				<tr>
					<td class="title"><?= $this->translate('news-admin-form-keywords') ?></td>
					<td class="value"><?= $this->controller->getListItemValue($this->dataRow, 'keywords'); ?></td>
				</tr>
				<tr>
					<td class="title"><?= $this->translate('news-admin-form-description') ?></td>
					<td class="value"><?= $this->controller->getListItemValue($this->dataRow, 'description'); ?></td>
				</tr>
				<tr>
					<td class="title"><?= $this->translate('news-admin-form-short-content') ?></td>
					<td class="value"><?= $this->controller->getListItemValue($this->dataRow, 'short_content'); ?></td>
				</tr>
				<tr>
					<td class="title"><?= $this->translate('news-admin-form-content') ?></td>
					<td class="value"><?= $this->dataRow->content ?></td>
				</tr>
			</table>
		</div>
	</div>
</div>
