<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?= $this->headTitle('Администрирование', 'PREPEND') ?>
<link rel="stylesheet" type="text/css" media="screen, print" href="<?php print $this->baseUrl ?>/js/libs/jquery_ui/1.8.4/css/smoothness/jquery-ui-1.8.4.custom.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php print $this->baseUrl ?>/css/jquery.jgrowl.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php print $this->baseUrl ?>/js/libs/datepick/redmond.datepick.css" />
<?= $this->headLink(); ?>
<link rel="stylesheet" type="text/css" media="screen, print" href="<?php print $this->baseUrl ?>/css/admin/admin.css" />
<link rel="stylesheet" type="text/css" media="print" href="<?php print $this->baseUrl ?>/css/admin/print.css" />
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/jquery.json.min.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/jquery.metadata.pack.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/jquery.bgiframe.pack.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/text.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/jquery.maskedinput-1.2.2.min.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/datepick/jquery.datepick.pack.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/datepick/jquery.datepick-ru.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/jquery_ui/1.8.4/js/jquery-ui-1.8.4.custom.min.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/layout/jquery.layout.min.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/jquery.jgrowl.min.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/libs/jquery.string.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl ?>/js/admin/admin.init.js"></script>
<script type="text/javascript">init('<?php print $this->baseUrl ?>');</script>
<?php $this->partial('js_tinymce_backend_includes.phtml',null,$this); ?>
<?= $this->headScript(); ?>
