<div id="footer">
    <div class="logo">Sfera</div>
    <div class="footer-menu">
        <ul>
            <li><a href="#">Sfera ADs</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Sfera News</a></li>
            <li><a href="#">Features</a></li>
            <li><a href="#">Sfera Blogs</a></li>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">Weather</a></li>
            <li><a href="#">User info</a></li>
        </ul>
    </div><!-- .footer-menu-->
    <div class="connect-with-us block">
        <div class="head"><h4>Connect with us</h4></div>
        <div class="list">
            <ul>
                <li><a href="#" class="fb">Facebook</a></li>
                <li><a href="#" class="tw">Twitter</a></li>
                <li><a href="#" class="gp">Google+</a></li>
            </ul>
        </div>
    </div>
    <div class="support-center block">
        <div class="head"><h4>Support Center</h4></div>
        <div class="list">
            <ul>
                <li>Tel: (844) 221-28-20</li>
                <li>Fax: (844) 221-28-20</li>
                <li>Email: <a href="mailto:contact@sfera.az">contact@sfera.az</a></li>
            </ul>
        </div>
    </div>

    <div class="copyright">
        <p>&copy; 2012 Sfera.az. All rights reserved</p>
    </div>

    <div class="artgen">
        <a href="http://www.artgen.com.ua/">Site development</a> Art generation studio
    </div>
</div><!-- #footer -->
