<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link rel="stylesheet" href="/css/reset.css"  type="text/css" media="screen, projection" />
    <link rel="stylesheet" href="/css/header.css" type="text/css" media="screen, projection" />
    <link rel="stylesheet" href="/css/footer.css" type="text/css" media="screen, projection" />
    <link rel="stylesheet" href="/css/scrollbar.css" type="text/css" media="screen, projection" />
    <link rel="stylesheet" href="/css/jquery.selectBox.css" type="text/css" media="screen, projection" />
    <link rel="stylesheet" href="/css/post-meta.css" type="text/css" media="screen, projection" />

    <!--[if lt IE 8]>
        <script src="/js/IE8.js"></script>
    <![endif]-->
    <script src="/js/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="/js/jquery-ui-1.8.17.custom.min.js" type="text/javascript"></script>
    <script src="/js/jquery.tinyscrollbar.min.js" type="text/javascript"></script>
    <script src="/js/jquery.customselectbox.min.js" type="text/javascript"></script>
    <script src="/js/site.js" type="text/javascript"></script>
    <script src="/js/shared.js" type="text/javascript"></script>
    <?= $this->partial('header.phtml') ?>
</head>
<?php
	$siteSettings = Zend_Registry::get('sitesettings');
?>
<body<?= $this->placeholder('bodyClass') ?>>
<div id="header-banner">
	<img src="/upload/banner-header.jpg" alt="banner-header" width="960" height="116" />
</div><!-- #header-banner-->

<div id="wrapper">

    <?= $this->partial('header_layout.phtml') ?>

    <?= $this->layout()->content ?>

    <?= $this->partial('footer_layout.phtml') ?>

</div><!-- #wrapper -->

</body>
</html>
