<div class="user-meta">
    <a href="<?= $this->getUrl('profile/id/'.$this->currentProfile->id) ?>" class="user-name"><?= $this->currentProfile->getfullName() ?></a>
    started folowing
    <a href="<?= $this->getUrl('profile/id/'.$this->storyItemValue->id) ?>" class="follower-name"><?= $this->storyItemValue->getfullName() ?></a>
    <span class="timestamp"><?= $this->formatDate($this->storyItem->added) ?></span>
</div>
<div class="users-block">
    <ul>
        <li style="background: url(/upload/avatar-01.jpg)"><a href="#" title="blogger name 1"></a></li>
        <li style="background: url(/upload/avatar-02.jpg)"><a href="#" title="blogger name 2"></a></li>
        <li style="background: url(/upload/avatar-03.jpg)"><a href="#" title="blogger name 3"></a></li>
        <li style="background: url(/upload/avatar-04.jpg)"><a href="#" title="blogger name 4"></a></li>
        <li style="background: url(/upload/avatar-05.jpg)"><a href="#" title="blogger name 5"></a></li>
        <li style="background: url(/upload/avatar-01.jpg)"><a href="#" title="blogger name 1"></a></li>
        <li style="background: url(/upload/avatar-02.jpg)"><a href="#" title="blogger name 2"></a></li>
        <li style="background: url(/upload/avatar-03.jpg)"><a href="#" title="blogger name 3"></a></li>
        <li style="background: url(/upload/avatar-04.jpg)"><a href="#" title="blogger name 4"></a></li>
        <li style="background: url(/upload/avatar-05.jpg)"><a href="#" title="blogger name 5"></a></li>
        <li style="background: url(/upload/avatar-01.jpg)"><a href="#" title="blogger name 1"></a></li>
        <li style="background: url(/upload/avatar-02.jpg)"><a href="#" title="blogger name 2"></a></li>
        <li style="background: url(/upload/avatar-03.jpg)"><a href="#" title="blogger name 3"></a></li>
        <li style="background: url(/upload/avatar-04.jpg)"><a href="#" title="blogger name 4"></a></li>
        <li style="background: url(/upload/avatar-05.jpg)"><a href="#" title="blogger name 5"></a></li>
        <li style="background: url(/upload/avatar-01.jpg)"><a href="#" title="blogger name 1"></a></li>
        <li style="background: url(/upload/avatar-02.jpg)"><a href="#" title="blogger name 2"></a></li>
        <li style="background: url(/upload/avatar-03.jpg)"><a href="#" title="blogger name 3"></a></li>
        <li style="background: url(/upload/avatar-04.jpg)"><a href="#" title="blogger name 4"></a></li>
        <li style="background: url(/upload/avatar-05.jpg)"><a href="#" title="blogger name 5"></a></li>
    </ul>
</div>
