<?php
	$this->headTitle($this->msgAdminTitle);
    $this->partial('js_grid_includes.phtml',null,$this);
    $this->headScript()->appendScript($this->render('admin/index/js/grid.js'));
    $this->headScript()->appendScript($this->render('admin/index/js/add.js'));
//	$this->headScript()->appendScript('var GridBaseUrl = "'.$this->getUrl("/admin/module/users/index/").'";');
//	$this->headScript()->appendScript('var subscriberList = "'.$this->subscriberList.'";');
//	$this->headScript()->appendScript('var activatedList = "'.$this->activatedList.'";');
//	$this->headScript()->appendScript('var statusList = "'.$this->statusList.'";');
?>
<div id="main">
	<div class="content">
		<div id="head">
			<h2><?= $this->msgAdminTitle ?></h2>
		</div>
		<div id="add-button-row">
			<div class="control">
				<?php if($this->checkPermission('users', 'admin_index', 'add')): ?>
					<span class="button" id="add-button">
						<button class="add-button"><?= $this->msgButtonAdd ?></button>
					</span>
				<?php endif; ?>
                <span class="button reset" id="cancel-button">
                    <a href="<?php echo $this->getUrl(''); ?>" class="cancel-action"><?= $this->msgButtonBack ?></a>
                </span>
                <span class="separator">
                    &nbsp;&nbsp;&nbsp;
                </span>
                <span class="button submit" id="submit-button">
                    <button id="submit-add-form" class="add-action"><?= $this->msgButtonSave ?></button>
                </span>
			</div>
		</div>
		<div id="add-row">
		<?= $this->partial('admin/index/form.phtml',null,$this) ?>
		</div>
		<br />
		<div id="grid-row">
			<table id="jqgridtable" class="scroll" cellpadding="0" cellspacing="0"></table>
			<div id="jqgridpager" class="scroll" style="text-align:center;"></div>
		</div>
	</div>
</div>
